import NavbarUser from "@/components/layouts/navbar-user";
import AdminSidebar from "@/components/layouts/sidebar/admin-sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <section className="dark:bg-neutral-800 bg-white relative  justify-center flex border dark:border-neutral-700 shadow-xl border-neutral-200 min-h-screen w-full overflow-hidden">
          <AdminSidebar />
          <main className="flex-1 dark:bg-neutral-800 bg-neutral-100 overflow-y-auto h-screen">
            <NavbarUser />
            <section className="px-8 py-2 pb-10">
            {children}
            </section>
          </main>
        </section>
      </body>
    </html>
  );
}
